version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202010-01

    steps:
      - checkout

      - run:
          name: Mix deps.get
          command: |
            set -x
            bash -c "mix deps.get && mix deps.compile"

      - run:
          name: Npm install in assets directory
          command: |
            set -x
            bash -c "cd assets && ls && npm install && node node_modules/webpack/bin/webpack.js --mode development"

      - run:
          name: Mix format
          command: |
            set -x
            bash -c "mix format --check-formatted"

      - run:
          name: Mix test
          command: |
            set -x
            bash -c "mix test"

      - run:
          name: Finish pipeline
          command: |
            set -x
            echo "Finish pipeline"
