workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/elixir:1.11.2
    steps:
      - checkout
      - run:
          name: Mix and Rebar install
          command: |
            set -x
            mix local.hex --force
            mix local.rebar --force
      - run:
          name: Mix deps.get
          command: |
            set -x
            bash -c "mix deps.get && mix deps.compile"
      - run:
          name: Mix format
          command: |
            set -x
            bash -c "mix format --check-formatted"
      - run:
          name: Mix test
          command: |
            set -x
            bash -c "mix test"
      - run:
          name: Finish pipeline
          command: |
            set -x
            echo "Finish pipeline"
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku main
          command: |
            set -x
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
