workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master

version: 2.1
orbs:
  heroku: circleci/heroku@1.2.4
jobs:
  build:
    docker:
      - image: circleci/elixir:1.11.3-node
    steps:
      - checkout
      - run:
          name: Mix and Rebar install
          command: |
            set -x
            mix local.hex --force
            mix local.rebar --force
      - run:
          name: Mix deps.get & compile
          command: |
            set -x
            bash -c "mix deps.get && mix deps.compile"
      - run:
          name: Set specific Node version
          command: |
            set -x
            curl -sSL "https://nodejs.org/dist/v14.15.4/node-v14.15.4-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v14.15.4-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
            node -v && npm -v
      - run:
          name: Npm install in assets directory
          command: |
            set -x
            bash -c "cd assets && npm i"
      - run:
          name: Mix format
          command: |
            set -x
            bash -c "mix format --check-formatted"
      - run:
          name: Mix test
          command: |
            set -x
            bash -c "mix test"
      - run:
          name: Finish CI pipeline
          command: |
            set -x
            echo "Finish CI pipeline"
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Heroku login
          command: |
            set -x
            heroku login
      - heroku/deploy-via-git
